test1/booktest/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/11/12 14:53
# @Author : WangShu
# @FileName: urls.py
# @Software: PyCharm
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    # 配置详细页url，\d+表示多个数字，小括号用于取值，建议复习下正则表达式
    url(r'^(\d+)$', views.detail),
]

test1/test1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('booktest.urls')),
]

test1/booktest/models.py
from django.db import models


# Create your models here.

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateField()

    def __str__(self):
        return "%d" % self.pk


class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=100)
    hBook = models.ForeignKey('BookInfo', on_delete=models.DO_NOTHING)

    def __str__(self):
        return "%d" % self.pk

test1/booktest/views.py
from django.shortcuts import render
from booktest.models import BookInfo


# 首页，展示所有图书
def index(reqeust):
    # 查询所有图书
    booklist = BookInfo.objects.all()
    # 将图书列表传递到模板中，然后渲染模板
    return render(reqeust, 'booktest/index.html', {'booklist': booklist})


# 详细页，接收图书的编号，根据编号查询，再通过关系找到本图书的所有英雄并展示
def detail(reqeust, id):
    # 根据图书编号对应图书
    book = BookInfo.objects.get(pk=id)
    # 将图书信息传递到模板中，然后渲染模板
    return render(reqeust, 'booktest/detail.html', {'book': book})

test1/templates/booktest/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>详细页</title>
</head>
<body>
{#输出图书标题#}
<h1>{{book.btitle}}</h1>
<ul>
    {#通过关系找到本图书的所有英雄，并遍历#}
    {%for hero in book.heroinfo_set.all%}
    {#输出英雄的姓名及描述#}
    <li>{{hero.hname}}---{{hero.hcontent}}</li>
    {%endfor%}
</ul>
</body>
</html>

test1/templates/booktest/index.html
<!DOCTYPE html>
<html>
<head>
    <title>首页</title>
</head>
<body>
<h1>图书列表</h1>
<ul>
    {#遍历图书列表#}
    {%for book in booklist%}
    <li>
     {#输出图书名称，并设置超链接，链接地址是一个数字#}
      <a href="{{book.id}}">{{book.btitle}}</a>
    </li>
    {%endfor%}
</ul>
</body>
</html>